runtime: python
env: flex

service: cdiibackendapi

env_variables:
  FLASK_APP: app.py

entrypoint: flask run --host=0.0.0.0 --port=$PORT

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.10"
